[package]
name = "analyze-task-schedule"
version = "0.1.0"
authors = ["onurzdg"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
log ="0.4.14"
env_logger = "0.9.0"

[dev-dependencies]
lazy_static = "1.4.0"
quickcheck = "1"
quickcheck_macros = "1"